# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaltStack', '0003_auto_20180820_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minions',
            name='ip',
            field=models.GenericIPAddressField(help_text='IP地址', unique=True, verbose_name='IP地址'),
        ),
    ]
