# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaltStack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minions',
            old_name='ipv4',
            new_name='ip',
        ),
    ]
