# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SaltStack', '0002_auto_20180820_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minions',
            old_name='online_time',
            new_name='last_online',
        ),
        migrations.RenameField(
            model_name='minions',
            old_name='test_time',
            new_name='last_test',
        ),
    ]
