# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-20 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaltStack', '0004_auto_20180820_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playbooks_previous',
            name='change',
            field=models.CharField(blank=True, default='', help_text='修改说明', max_length=100, null=True, verbose_name='修改说明'),
        ),
    ]
