# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-21 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SaltStack', '0006_auto_20180820_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minions',
            name='status',
            field=models.IntegerField(choices=[(0, '离线'), (1, '在线'), (2, '检测中'), (3, '异常')], default=2, help_text='联机状态', verbose_name='联机状态'),
        ),
    ]
