# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 10:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SaltStack', '0007_auto_20180821_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='status_flow',
            field=models.ForeignKey(blank=True, help_text='任务流程描述', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='SaltStack.Jobs', verbose_name='任务流程描述'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.IntegerField(choices=[(0, '排队中'), (1, '执行中'), (2, '已完成'), (3, '异常')], default=0, help_text='任务当前状态', verbose_name='任务当前状态'),
        ),
    ]
