# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-06 09:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderKingdom', '0002_auto_20180806_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitordata',
            options={'verbose_name_plural': '检测数据'},
        ),
        migrations.AddField(
            model_name='cdn',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='domain',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='node',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='project',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AddField(
            model_name='statuscode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='cdn',
            name='cdn',
            field=models.CharField(default=None, max_length=60, null=True, verbose_name='CDN厂商名称'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='cert_valid_date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='证书有效期'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='cert_valid_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='证书剩余天数'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='check',
            field=models.BooleanField(default=True, verbose_name='是否检查'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='detection_interval',
            field=models.IntegerField(default=300, verbose_name='检查间隔'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain',
            field=models.CharField(max_length=60, unique=True, verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SpiderKingdom.StatusCode', verbose_name='域名状态'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='trigger',
            field=models.IntegerField(default=1, verbose_name='连续异常几次才警告'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='warning',
            field=models.BooleanField(default=True, verbose_name='是否警告'),
        ),
        migrations.AlterField(
            model_name='monitordata',
            name='datetime',
            field=models.DateTimeField(db_index=True, verbose_name='检测时间'),
        ),
        migrations.AlterField(
            model_name='monitordata',
            name='http_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='http状态码'),
        ),
        migrations.AlterField(
            model_name='monitordata',
            name='total_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='请求耗时'),
        ),
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='节点描述'),
        ),
        migrations.AlterField(
            model_name='node',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='节点IP'),
        ),
        migrations.AlterField(
            model_name='node',
            name='node',
            field=models.CharField(max_length=20, unique=True, verbose_name='节点名称'),
        ),
        migrations.AlterField(
            model_name='node',
            name='online',
            field=models.IntegerField(choices=[(0, '在线'), (1, '离线')], default=0, verbose_name='在线状态'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='statuscode',
            name='status_code',
            field=models.IntegerField(unique=True, verbose_name='状态码'),
        ),
        migrations.AlterField(
            model_name='statuscode',
            name='status_description',
            field=models.CharField(max_length=60, unique=True, verbose_name='状态描述'),
        ),
    ]
