# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderKingdom', '0004_auto_20180807_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='nodes',
            field=models.ManyToManyField(to='SpiderKingdom.Node', verbose_name='节点'),
        ),
    ]
