# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderKingdom', '0005_auto_20180808_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitordata',
            name='detection_interval',
            field=models.IntegerField(blank=True, null=True, verbose_name='检查间隔'),
        ),
    ]
