# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-07 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderKingdom', '0003_auto_20180806_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventlog',
            name='url',
        ),
        migrations.AddField(
            model_name='eventlog',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpiderKingdom.Domain', verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='cdn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpiderKingdom.CDN', verbose_name='CDN厂商'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='nodes',
            field=models.ManyToManyField(blank=True, null=True, to='SpiderKingdom.Node', verbose_name='节点'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpiderKingdom.Project', verbose_name='项目'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpiderKingdom.StatusCode', verbose_name='状态描述'),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SpiderKingdom.Node', verbose_name='节点'),
        ),
        migrations.AlterField(
            model_name='monitordata',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpiderKingdom.Domain', verbose_name='域名'),
        ),
        migrations.AlterField(
            model_name='monitordata',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpiderKingdom.Node', verbose_name='节点名称'),
        ),
    ]
