# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderKingdom', '0008_auto_20180816_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='nodes',
            field=models.ManyToManyField(blank=True, help_text='检测节点ID', to='SpiderKingdom.Node', verbose_name='节点'),
        ),
    ]
