# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-22 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SpiderKingdom', '0009_auto_20180816_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('domain', models.ForeignKey(blank=True, help_text='域名ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpiderKingdom.Domain', verbose_name='域名')),
                ('node', models.ForeignKey(blank=True, help_text='节点ID', null=True, on_delete=django.db.models.deletion.CASCADE, to='SpiderKingdom.Node', verbose_name='节点')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='eventlog',
            name='node',
        ),
        migrations.DeleteModel(
            name='EventLog',
        ),
    ]
